******************************************;
*** Begin Scoring Code from PROC DMINE ***;
******************************************;

length _WARN_ $ 4;
label _WARN_ = "Warnings";


/*----G_horsepower begin----*/
length _NORM3 $ 3;
_NORM3 = put( horsepower , $3. );
%DMNORMIP( _NORM3 )
drop _NORM3;
select(_NORM3);
  when('100' ) G_horsepower = 1;
  when('102' ) G_horsepower = 1;
  when('103' ) G_horsepower = 1;
  when('105' ) G_horsepower = 1;
  when('107' ) G_horsepower = 1;
  when('108' ) G_horsepower = 1;
  when('110' ) G_horsepower = 1;
  when('112' ) G_horsepower = 1;
  when('115' ) G_horsepower = 3;
  when('116' ) G_horsepower = 3;
  when('120' ) G_horsepower = 1;
  when('122' ) G_horsepower = 1;
  when('125' ) G_horsepower = 1;
  when('129' ) G_horsepower = 0;
  when('130' ) G_horsepower = 0;
  when('135' ) G_horsepower = 1;
  when('137' ) G_horsepower = 0;
  when('138' ) G_horsepower = 0;
  when('139' ) G_horsepower = 1;
  when('140' ) G_horsepower = 0;
  when('142' ) G_horsepower = 0;
  when('145' ) G_horsepower = 0;
  when('148' ) G_horsepower = 0;
  when('149' ) G_horsepower = 0;
  when('150' ) G_horsepower = 0;
  when('153' ) G_horsepower = 0;
  when('155' ) G_horsepower = 0;
  when('158' ) G_horsepower = 0;
  when('160' ) G_horsepower = 0;
  when('165' ) G_horsepower = 0;
  when('170' ) G_horsepower = 0;
  when('175' ) G_horsepower = 0;
  when('180' ) G_horsepower = 0;
  when('190' ) G_horsepower = 0;
  when('198' ) G_horsepower = 0;
  when('200' ) G_horsepower = 0;
  when('208' ) G_horsepower = 0;
  when('210' ) G_horsepower = 0;
  when('215' ) G_horsepower = 0;
  when('220' ) G_horsepower = 0;
  when('225' ) G_horsepower = 0;
  when('46' ) G_horsepower = 3;
  when('48' ) G_horsepower = 7;
  when('49' ) G_horsepower = 4;
  when('52' ) G_horsepower = 4;
  when('53' ) G_horsepower = 5;
  when('54' ) G_horsepower = 2;
  when('58' ) G_horsepower = 6;
  when('60' ) G_horsepower = 4;
  when('61' ) G_horsepower = 5;
  when('62' ) G_horsepower = 5;
  when('63' ) G_horsepower = 6;
  when('65' ) G_horsepower = 6;
  when('66' ) G_horsepower = 6;
  when('67' ) G_horsepower = 5;
  when('68' ) G_horsepower = 5;
  when('69' ) G_horsepower = 5;
  when('70' ) G_horsepower = 5;
  when('71' ) G_horsepower = 4;
  when('72' ) G_horsepower = 1;
  when('74' ) G_horsepower = 5;
  when('75' ) G_horsepower = 4;
  when('76' ) G_horsepower = 4;
  when('77' ) G_horsepower = 3;
  when('78' ) G_horsepower = 4;
  when('79' ) G_horsepower = 3;
  when('80' ) G_horsepower = 4;
  when('82' ) G_horsepower = 4;
  when('83' ) G_horsepower = 4;
  when('84' ) G_horsepower = 4;
  when('85' ) G_horsepower = 3;
  when('86' ) G_horsepower = 3;
  when('87' ) G_horsepower = 3;
  when('88' ) G_horsepower = 3;
  when('89' ) G_horsepower = 3;
  when('90' ) G_horsepower = 3;
  when('91' ) G_horsepower = 1;
  when('92' ) G_horsepower = 4;
  when('93' ) G_horsepower = 3;
  when('94' ) G_horsepower = 2;
  when('95' ) G_horsepower = 2;
  when('96' ) G_horsepower = 4;
  when('97' ) G_horsepower = 2;
  when('98' ) G_horsepower = 1;
  when('?' ) G_horsepower = 4;
  otherwise substr(_WARN_, 2, 1) = 'U'; 
end;
label G_horsepower="Grouped Levels for  horsepower";
/*----horsepower end----*/


****************************************;
*** End Scoring Code from PROC DMINE ***;
****************************************;
